'use client'
import { Button } from "../ui/button"
import { Download } from "lucide-react"


export default function DownloadSummaryButton({title, summaryText , fileName , createdAt}:{title:string , summaryText:string , fileName:string , createdAt:string}) {
    const handleDownload = ()=>{
        const summaryContent = 
`# ${title}\n
Generated Summary
Generated on : ${new Date(createdAt).toLocaleDateString()}
${summaryText}
Original File : ${fileName}
Generated By Summarix`

        const blob = new Blob([summaryContent], {type:'text/plain'});
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a')
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi,'_')}.txt`;
        document.body.appendChild(link);
        link.click();

        document.body.removeChild(link)
        URL.revokeObjectURL(url)

        
    }

  return (
    <div>
        <Button onClick={handleDownload} variant='ghost' size='sm' className="h-8 px-3 text-green-700 hover:text-green-600 hover:bg-green-50 bg-green-100">
             <Download className="h-4 w-4 mr-1"/>
            Download Summary
        </Button>
    </div>
     
  )
}
